### Estimador para Callaway e Sant'Anna (2021)

**ideia geral**

A ideia aqui é partir do estimador de Sant'Anna e Zhao (2020) e adaptá-lo para o caso de múltiplos períodos de tratamento, como proposto por Callaway e Sant'Anna (2021). Vamos utilizar o pacote em python do DoubleML para implementar o estimador. E compará-lo com o estimador `differences` do python.

**Objetivo do Projeto**

* Implementar o estimador de Callaway & Sant’Anna (2021) para múltiplos períodos de tratamento, adaptando o DoubleML (que já possui o estimador de Sant'Anna & Zhao, 2020).
* Comparar os resultados com o estimador differences disponível no Python.
* Analisar consistência, precisão, robustez e desempenho computacional dos dois 


!pip install differences
!pip install doubleml

In [6]:
from differences import ATTgt, simulate_data
df = simulate_data()
df

c:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\linearmodels\panel\utility.py:616: FutureWarning: 'A-DEC' is deprecated and will be removed in a future version, please use 'YE-DEC' instead.
  time = [dt for dt in date_range("1-1-1900", periods=t, freq="A-DEC")]

                     y        x0         w  cat.0  cat.1  effect  cohort  \
entity time
e0     1900  -8.339645  0.160245  3.729827      0      0     0.0  1904.0
       1901 -17.509240 -1.933404  1.691201      0      0     0.0  1904.0
       1902  15.396063 -0.056813  1.786326      0      0     0.0  1904.0
       1903  -1.840331  0.810118  1.741609      0      0     0.0  1904.0
       1904 -15.963023  0.101205  0.806004      0      0     0.0  1904.0
...                ...       ...       ...    ...    ...     ...     ...
e999   1903  17.429081  1.355023  0.688025      0      0    10.0  1902.0
       1904  25.095168 -0.381267  1.952084      0      0    20.0  1902.0
       1905  27.472180 -0.258604  1.801049      0      0    30.0  1902.0
       1906  49.068843  1.504564  0.616657      0      0    40.0  1902.0
       1907  37.521049  0.472740  0.674045      0      0    50.0  1902.0

             intensity
entity time
e0     1900       5.25
       1901       5.25
       1902       5.25
       1903       5.25
       1904       5.25
...                ...
e999   1903      10.00
       1904      10.00
       1905      10.00
       1906      10.00
       1907      10.00

[8000 rows x 8 columns]

In [7]:
att_gt = ATTgt(data=df, cohort_name='cohort')
att_gt.fit(formula='y')

Computing ATTgt [workers=1]   100%|████████████████████| 21/21 [00:00<00:00, 158.53it/s]

                        ATTgtResult                                            \
                                     analytic pointwise conf. band
                                ATT std_error                lower      upper
cohort base_period time
1902   1900        1901   -0.967180  1.368086            -3.648579   1.714218
       1901        1902    0.804454  1.373537            -1.887630   3.496538
                   1903    9.566526  1.324877             6.969814  12.163238
                   1904   21.030647  1.384353            18.317364  23.743930
                   1905   31.164536  1.365182            28.488828  33.840244
                   1906   38.620286  1.330408            36.012734  41.227838
                   1907   52.121565  1.374356            49.427877  54.815253
1903   1900        1901    0.037480  1.339879            -2.588635   2.663596
       1901        1902    0.030075  1.337026            -2.590447   2.650598
       1902        1903   -1.870289  1.286616            -4.392011   0.651433
                   1904    0.225787  1.403432            -2.524890   2.976464
                   1905    1.489896  1.267572            -0.994500   3.974292
                   1906    1.018869  1.345045            -1.617371   3.655108
                   1907    2.941520  1.359934             0.276098   5.606943
1904   1900        1901    0.439778  1.354917            -2.215811   3.095368
       1901        1902    0.287032  1.290460            -2.242223   2.816287
       1902        1903   -2.396916  1.345653            -5.034348   0.240516
       1903        1904    3.371839  1.289699             0.844077   5.899602
                   1905    8.227096  1.324789             5.630558  10.823633
                   1906   11.147300  1.315644             8.568685  13.725914
                   1907   18.689660  1.283348            16.174344  21.204976



                        zero_not_in_cband
cohort base_period time
1902   1900        1901
       1901        1902
                   1903                 *
                   1904                 *
                   1905                 *
                   1906                 *
                   1907                 *
1903   1900        1901
       1901        1902
       1902        1903
                   1904
                   1905
                   1906
                   1907                 *
1904   1900        1901
       1901        1902
       1902        1903
       1903        1904                 *
                   1905                 *
                   1906                 *
                   1907                 *

In [8]:
att_gt.aggregate('event')

                EventAggregation                                            \
                                  analytic pointwise conf. band
                             ATT std_error                lower      upper
relative_period
-3                      0.439778  1.354917            -2.215811   3.095368
-2                      0.162256  0.800754            -1.407193   1.731706
-1                     -1.110980  0.628506            -2.342829   0.120869
 0                      0.768758  0.613894            -0.434453   1.971969
 1                      6.015370  0.743925             4.557304   7.473435
 2                     11.247134  0.834527             9.611491  12.882778
 3                     16.993205  0.886719            15.255267  18.731143
 4                     20.847717  1.232809            18.431457  23.263978
 5                     52.121565  1.374356            49.427877  54.815253



                zero_not_in_cband
relative_period
-3
-2
-1
 0
 1                              *
 2                              *
 3                              *
 4                              *
 5                              *

In [3]:
from differences import att_gt

ImportError: cannot import name 'att_gt' from 'differences' (c:\Users\danie\AppData\Local\Programs\Python\Python311\Lib\site-packages\differences\__init__.py)

In [ ]:
# 1. Importar pacotes
import pandas as pd
import numpy as np
from doubleml import DoubleMLData, DoubleMLDID
from differences import att_gt
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor

# 2. Carregar base
df = pd.read_csv('bacon_example.csv')

# 3. Preparar dados: definir G, cohort, treated, etc.

# 4. Implementar estimador via DoubleML adaptado para múltiplos períodos

# 5. Implementar estimador via differences

# 6. Comparar resultados: tabelas e gráficos

# 7. Análise crítica